### PR TITLE
 Fix language codes not actually specific to snippets

### LINKED ISSUE #678: Assign langCodes correctly when combining snippets objects
If we combine two different language snippets objects (e.g. to fill in gaps in a translation) and then do interpolation, the wrong language code will be propagated to the snippets in one of the objects (based on which one provided the top-level `langCode` value). To fix this, we should do the interpolation process on snippets before combining them.

### PR DESCRIPTION
**Pull request by ethanbb**
Fixes #678. Interpolates snippet objects _before_ merging them, so that the spans created from the snippets in each object get the correct `lang` code during the interpolation process. You can see the change by setting the default language in `App.js` to `de` instead of `en`, and comparing snippets that are already in German with those that are currently defaulted to English.

I also noticed that the `<html>` tag had an invalid `lang` attribute (`[object Object]`), since the `langCode` was also getting wrapped in a `<span>`. I changed the interpolation function to not wrap `langCode`, but just to be doubly safe, I also changed the `<html>` attribute to use the language code from the state directly rather than reading from the snippets.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -30,15 +30,15 @@ class App extends Component {
   };
 
   render () {
-    var { snippets } = this.state;
+    var { language, snippets } = this.state;
```
Comment (knod) [inline src/App.js]: Note for future: We should probably change this to `langCode` too.

File: src/utils/getTextForLanguage.js [hunk 2]
```diff
@@ -24,23 +26,20 @@ const mergeCustomizer = function (objValue, srcValue) {
  * doesn't exist, it warns the coder and returns English.
  */
 const getTextForLanguage = function (langName) {
+  if (langName === 'en') {
```
Comment (knod) [inline src/utils/getTextForLanguage.js]: Also note for future: This probably should also be `langCode`.

File: src/utils/getTextForLanguage.js [hunk 3]
```diff
@@ -24,23 +26,20 @@ const mergeCustomizer = function (objValue, srcValue) {
...
     // so that we fall back to English if a particular field is missing.
-    snippetsTemplate = mergeWith({}, english, localizations[ langName ], mergeCustomizer);
+    return mergeWith({}, interpolatedEnglish, interpolatedSnippets, mergeCustomizer);
 
   } else {
-
     console.warn('There\'s no localization for ' + langName + '. Defaulting to English.');
-    snippetsTemplate = english;
-
+    return interpolatedEnglish;
```
Comment (knod) [inline src/utils/getTextForLanguage.js]: It's a bit confusing that we're returning something called 'interpolatedEnglish'. That's a wording issue, though, and we just tweak it in a different PR.

Comment (knod) [reply src/utils/getTextForLanguage.js]: Oh, my bad - this only happens if there isn't a matching language. Nvm.

**Comment by knod** [comment]
Adding label to remind myself of possible todo items.
