### PR TITLE
Fixes #967, 'Household' section crashing and burning

### LINKED ISSUE #967: 'Household' section burning
### Replicate:
1. Go to 'Household' section

### Result I'd Expect:
- No error

### Actual Result:
- Error

### Environment:
App version or commit id at the time: 71c168723255c7abb67d9d4c96573ddbb5696bbb

### Other Notes
We really have to switch to non-shallow tests. Thought I was covered on this one!

### PR DESCRIPTION
**Pull request by knod**
Sorry folks, this was my bad. Head's underwater somewhere again.

### CODE REVIEW

File: src/forms/inputs.js [hunk 1]
```diff
@@ -184,6 +184,12 @@ class ManagedNumberField extends Component {
     var { valid, focused, focusedVal }                = this.state;
     var { value, name, className, format, otherData } = this.props;
 
+    // @todo Bad var name. Find more useful name for this.
+    let id = name;
```
Comment (pporfilio) [inline src/forms/inputs.js:188]: Maybe something like `constructedId` or `augmentedId`?

**Review by pporfilio — APPROVED** [review]
This appears to resolve the crash on the Household section and seems like a nice change to not require an interval to be specified.

File: src/forms/inputs.js (hunk 1 above)
Comment (knod) [reply src/forms/inputs.js:188]: Oh, sorry. That wasn't specific and was put in the wrong place. I meant `interval`. Something like `idSuffix` might be useful for that. @todo
