### PR TITLE
Change localization data to object clone instead of object reference

### LINKED ISSUE #947: .langCode incorrectly displaying in each section or localization report
Report contains an entry like the following:
"aboutPage.langCode should exist."

`.langCode` exists as a key at the top of the localization object only.  It's being treated as if it's a key in every object.

### PR DESCRIPTION
**Pull request by jlangevin**
Fixes #947 .  Also moves List.Item key to ReportListItems to fix duplicate keys warning.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -88,6 +88,10 @@ class App extends Component {
       },
       distrustConfirmed: false,
     };
+
+
+
+    console.log(getTextForLanguage(`zh`));
```
Comment (knod) [inline src/App.js]: I've done this a million times myself

Comment (jlangevin) [reply src/App.js]: Ah, that was leftover from our call this morning.  Sorry about that.  Good catch.  Thanks!

**Review by knod — APPROVED** [review]
A bit of a heavy PR, but the changes are lookin' good to me!
