### PR TITLE
Fixes #545, Form routes

### LINKED ISSUE #545: Back button in browser behavior unexpected, `Forms` to pages/routes instead

### PR DESCRIPTION
**Pull request by turnerhayes**
Test plan:

- Mark one or more of the benefits in the first step.
- Click on steps in the step bar. The URL should change and you should not see any dialog asking you to confirm navigation.
- Click on a link outside the visit workflow (e.g. Home, About)
- You should see a navigation confirmation dialog

- Reload the page while on one of the later steps (not the first step)
- Before the page changes, you should see a navigation confirmation dialog
- After reloading, the visit should go back to the first step

- If you have not selected any benefits, you should not see any confirmation dialog, even when going outside the visit workflow.

### CODE REVIEW

File: src/containers/VisitPage.js [hunk 1]
```diff
@@ -62,37 +52,19 @@ class VisitPage extends Component {
...
-      {
-        form:              PredictionsStep,
-        key:               'predictions',
-        updateClientValue: this.changeFuture,
-      },//,
-    //  { title: 'Graphs', form: ResultsGraph }
-    ];  // end this.steps {}
+  componentDidMount() {
+    // If the user has refreshed the page while they were on a later step, then we will
+    // go back to that step, but since the client data is currently stored in memory, the
```
Comment (knod) [inline src/containers/VisitPage.js]: 'isn't stored in memory', I think

Comment (knod) [reply src/containers/VisitPage.js]: This also makes it sound like returning to the current step is the currently expected behavior.

Comment (knod) [reply src/containers/VisitPage.js]: Hmm. 'If the user... later step, they'd usually be automatically sent back to that step...'?

File: src/containers/VisitPage.js [hunk 2]
```diff
@@ -221,55 +193,55 @@ class VisitPage extends Component {
...
   };
-
+  
   previousStep = () => {
-    this.setState((prevState) => {
-      return { currentStep: prevState.currentStep - 1 };
-    });
+    const prevStepIndex = this.getCurrentStepIndex() - 1;
+
+    if (prevStepIndex < 0) {
```
Comment (knod) [inline src/containers/VisitPage.js:206]: What would call this function that would go below 0? The first form section doesn't have a 'Previous Step' button, so unless the navigation 'back' button does it, I'm not sure what would.

File: src/containers/VisitPage.js [hunk 3]
```diff
@@ -62,37 +52,19 @@ class VisitPage extends Component {
...
-    ];  // end this.steps {}
+  componentDidMount() {
+    // If the user has refreshed the page while they were on a later step, then we will
+    // go back to that step, but since the client data is currently stored in memory, the
+    // client data will be lost. So if we are loading on a step that is not the first step,
+    // go back to the first step to start again
+    const firstStepURL = `${this.getPathPrefix()}/${STEPS[ 0 ].key}`;
 
-  };  // End constructor()
+    if (this.props.history.location !== firstStepURL) {
```
Comment (knod) [inline src/containers/VisitPage.js]: Is this needed? If you're on the first step, you can still go to the first step without difficulty. Is it heavy to replace history and navigate to a step? Are there other reasons to avoid it?

**Review by knod — COMMENTED** [review]
I'm pausing here to say great work! This is some awesome looking stuff! I'm not sure anything I've found so far is blocking, though I do have to take another go to look more thoroughly and I need to test it out. Most of these comments are just clean up notes and don't necessarily need to be addressed right now.

File: src/containers/VisitPage.js [hunk 4]
```diff
@@ -345,7 +320,7 @@ class VisitPage extends Component {
          * point. Perhaps a user's page should be a route
          * in VisitPage? Like our form sections will be? */}
```
Comment (knod) [inline src/containers/VisitPage.js]: If you feel like it, you can probably update this comment ;)

File: src/containers/VisitPage.js (hunk 1 above)
Comment (turnerhayes) [reply src/containers/VisitPage.js]: The intent was to say "the way we currently store client data is in memory, so if you leave the page, it'll be gone". So the intent of this code is to redirect the user to the first step so that they can re-enter the data. I can try to reword it if it's not clear enough.

File: src/containers/VisitPage.js (hunk 3 above)
Comment (turnerhayes) [reply src/containers/VisitPage.js]: I had some issues with React Router throwing errors to the console when transitioning to the same page.

File: src/containers/VisitPage.js (hunk 2 above)
Comment (turnerhayes) [reply src/containers/VisitPage.js:206]: True; this is basically a sanity-check. Same with the next-step bit.

File: src/containers/VisitPage.js (hunk 1 above)
Comment (knod) [reply src/containers/VisitPage.js]: It's not blocking, so we can deal with it another time, but I found it unclear and rewording was what I was trying to describe.

File: src/containers/VisitPage.js (hunk 2 above)
Comment (knod) [reply src/containers/VisitPage.js:206]: Futureproofing, but maybe worth it. 👍

File: src/containers/VisitPage.js (hunk 3 above)
Comment (knod) [reply src/containers/VisitPage.js]: Ah, got it! A comment to that effect would probably be useful to someone trying to tighten up the code in the future.

File: src/components/StepBar.js [hunk 5]
```diff
@@ -1,15 +1,17 @@
 import React from 'react';
 import { Step } from 'semantic-ui-react';
 
-const StepBar = ({ steps, currentStepIndex, goToStep, snippets }) => {
+import { STEPS } from '../constants';
```
Comment (knod) [inline src/components/StepBar.js:4]: @todo for a later refactor - the name and location of `constants` is a big ambiguous. We have plenty of them around - a bunch for the benefit program logic, etc. These constants are specifically for form sections. They might find a better home with the form sections themselves and maybe a more specific name until we have something we need to add to the file.

File: src/components/MainMenu.js [hunk 6]
```diff
@@ -13,8 +13,16 @@ const MainMenu = function ({ snippets }) {
       secondary
       size='large'>
 
-      <Menu.Item><Link className="main-nav" to="/">{ snippets.i_homeNav }</Link></Menu.Item>
-      <Menu.Item><Link className="main-nav" to="/about">{ snippets.i_aboutNav }</Link></Menu.Item>
+      <Menu.Item><Link
```
Comment (knod) [inline src/components/MainMenu.js]: Just noting that 'lint-staged' isn't working well here because I suspect this wasn't one of your staged files.

File: src/components/prompts/ReactRouterLeaveListener.js [hunk 7]
```diff
@@ -40,14 +40,29 @@ class ReactRouterLeaveListener extends React.Component {
...
+      ) {
+        return true;
+      }
+    }
+
+    return `If you leave you'll lose this data. Are you sure you want to leave?`;
+  };
+
   render() {
     const { isBlocking } = this.props;
```
Comment (knod) [inline src/components/prompts/ReactRouterLeaveListener.js:58]: Another option to think about might be to leverage this prop. The parent could determine whether the prompt should show beforehand, since it knows what step it's on anyway.

Comment (knod) [reply src/components/prompts/ReactRouterLeaveListener.js:58]: @todo To consider for possible later refactor

File: src/containers/VisitPage.js [hunk 8]
```diff
@@ -345,7 +320,7 @@ class VisitPage extends Component {
...
         { this.state.redirect ? (
-          <Redirect to={ `/detail/${this.state.clientInfo.clientId}` } />
+          <Redirect to={ `/detail/${this.state.clientId}` } />
```
Comment (knod) [inline src/containers/VisitPage.js]: This is `this.props.clientId` now, right?

File: src/containers/VisitPage.js [hunk 9]
```diff
@@ -360,17 +335,28 @@ class VisitPage extends Component {
             minWidth='874.5'
             style={{ padding: '14px 0' }}>
             <StepBar
-              currentStepIndex={ this.state.currentStep }
-              steps={ this.steps }
+              currentStepKey={ this.props.stepKey }
```
Comment (knod) [inline src/containers/VisitPage.js:334]: From what I can tell, this could be `step.key` here, which might be more consistent with how it's being used further down.

Comment (knod) [reply src/containers/VisitPage.js:334]: Non-blocking, @todo

File: src/containers/VisitPage.js [hunk 10]
```diff
@@ -360,17 +335,28 @@ class VisitPage extends Component {
...
-            { this.getCurrentStep(navData) }
+            <StepComponent
+              component={ step.form }
+              snippets={ snippets[ step.key ] }
+              updateClientValue={
+                step.time === 'current' ?
+                  this.changeCurrent :
+                  this.changeFuture
+              }
+              currentStep={ stepIndex }
```
Comment (knod) [inline src/containers/VisitPage.js:348]: @todo Is this still being used somewhere or can we get rid of it?

File: src/containers/VisitPage.js [hunk 11]
```diff
@@ -360,17 +335,28 @@ class VisitPage extends Component {
...
+              currentStepKey={ this.props.stepKey }
               goToStep={ this.goToStep }
               snippets={ this.state.snippets.stepBar } />
           </Responsive>
           <div
             className="flex-item flex-column"
             style={{ padding: '14px 0' }}>
-            { this.getCurrentStep(navData) }
+            <StepComponent
+              component={ step.form }
```
Comment (knod) [inline src/containers/VisitPage.js:341]: @todo Do the sections use their own component?

File: src/containers/VisitPage.js (hunk 8 above)
Comment (turnerhayes) [reply src/containers/VisitPage.js]: Yes! Good catch!

File: src/components/MainMenu.js (hunk 6 above)
Comment (turnerhayes) [reply src/components/MainMenu.js]: I believe I may have run `npm run lint` which changed this. Not 100% sure.

File: src/components/StepBar.js (hunk 5 above)
Comment (turnerhayes) [reply src/components/StepBar.js:4]: Good point. We could have a single master constants file, but you're right that it might be better to have more specific constants modules.

**Review by knod — DISMISSED** [review]
I've only looked through this thoroughly about four times, so I can't be sure I've caught everything, but it's looking good to me! Though some buttons can't be tested because of that bug.

Sorry I ended up doing so much thinking aloud in here. I will aim for better in the future.

**Review by knod — DISMISSED** [review]
Lookin' good to me!

**Review by knod — APPROVED** [review]
Looking good other than a visual bug introduced earlier!

File: src/components/prompts/ReactRouterLeaveListener.js (hunk 7 above)
Comment (knod) [reply src/components/prompts/ReactRouterLeaveListener.js:58]: @turnerhayes : Did you have any thoughts on this?

Comment (turnerhayes) [reply src/components/prompts/ReactRouterLeaveListener.js:58]: This is the only way I could find to get the destination location on navigation.
